
global:
  scrape_interval: 15s # How often Prometheus will scrape metrics.

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
#  - job_name: prometheus
#    static_configs:
#      - targets:
#          - prometheus:9090
#  - job_name: node
#    static_configs:
#        - targets:
#            - node-exporter:9100